{{- $fullName := .Values.gitlab.app -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName | quote }}
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ $fullName | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: {{ $svcPort }}
    protocol: TCP
    targetPort: main-port
